# Generated by Django 2.0.2 on 2019-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(verbose_name='Fecha de inicio')),
                ('hasta', models.DateField(verbose_name='Fecha de fin')),
                ('cant_dias', models.PositiveIntegerField(verbose_name='Días trabajados')),
                ('cant_dias_dieta', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Días dieta')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoExtraordinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(verbose_name='Fecha de inicio')),
                ('hasta', models.DateField(verbose_name='Fecha de fin')),
                ('cant_horas', models.PositiveIntegerField(verbose_name='Cantidad de horas')),
            ],
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de solicitud')),
                ('cant_dias', models.PositiveIntegerField(verbose_name='Cantidad de días')),
                ('desde', models.DateField(verbose_name='Fecha Inicio')),
                ('hasta', models.DateField(verbose_name='Fecha Fin')),
                ('incorporacion', models.DateField(verbose_name='Fecha Fin')),
                ('horas', models.PositiveIntegerField(verbose_name='Cantidad de horas a descontar')),
                ('horas1', models.PositiveIntegerField(default=0, verbose_name='Cantidad de horas a descontar mes próximo')),
                ('jefe_area', models.CharField(max_length=60, verbose_name='Jefe de Área')),
                ('director', models.CharField(max_length=60, verbose_name='Aprobado:')),
            ],
        ),
    ]
