# Generated by Django 2.0.2 on 2019-08-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adm', '0001_initial'),
        ('ges_trab', '0002_auto_20190509_1122'),
        ('entrada_datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('factor', models.DecimalField(decimal_places=1, max_digits=2)),
                ('siglas', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Formato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formato', models.CharField(max_length=6)),
                ('factor', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2)),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('OT', 'Obra Turismo'), ('VT', 'Vivienda para Turismo')], default='', max_length=2)),
                ('horas_a2', models.PositiveIntegerField()),
                ('gesc', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='adm.EscalaSalarial')),
                ('orden_trab', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='entrada_datos.OT')),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=210)),
                ('cant', models.PositiveIntegerField(default=1)),
                ('fecha_vpc', models.DateField(blank=True, editable=False, null=True)),
                ('vpc', models.CharField(choices=[('No', 'No'), ('Si', 'Si')], default='No', editable=False, max_length=2)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('tarifa', models.DecimalField(decimal_places=6, default=0.0, editable=False, max_digits=8)),
                ('horas_creadas', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('estado', models.CharField(choices=[('V', 'V'), ('GE', 'GE'), ('VPC', 'VPC')], default='', editable=False, max_length=3)),
                ('fecha_pago', models.DateField(blank=True, editable=False, null=True)),
                ('valor_retenido', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('porciento', models.CharField(choices=[('1.0', '100%'), ('0.7', '70%'), ('0.3', '30%')], default='', max_length=3)),
                ('last_rev', models.IntegerField(blank=True, editable=False, null=True)),
                ('orden_servicio', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('corte', models.CharField(blank=True, default='', max_length=22, null=True)),
                ('horas_creadas_real', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                ('valor_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('valor_retenido_real', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('valor_total_real', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('os_vpc', models.CharField(blank=True, default='', editable=False, max_length=7, null=True)),
                ('rev_vpc', models.IntegerField(blank=True, editable=False, null=True)),
                ('actividad', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='entrada_datos.Actividad')),
                ('especialidad', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='prenomina15.Especialidad')),
                ('formato', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='prenomina15.Formato')),
                ('objeto', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='prenomina15.Objeto')),
                ('obra', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='prenomina15.Obra')),
                ('trabajador', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Trabajador_del_Plano', to='ges_trab.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rev', models.IntegerField(editable=False)),
                ('fecha_revision', models.DateField()),
                ('entregado', models.CharField(blank=True, max_length=15, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_estado', models.DateField()),
                ('fecha_vpc', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('GE', 'GE'), ('V', 'V'), ('VPC', 'VPC')], default='GE', max_length=3)),
                ('plano', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prenomina15.Plano')),
            ],
        ),
        migrations.CreateModel(
            name='SalarioMax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tipo', models.CharField(choices=[('OT', 'Obra Turismo'), ('VT', 'Vivienda para Turismo')], default='', max_length=2)),
                ('grupo_esc', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='adm.EscalaSalarial')),
            ],
        ),
        migrations.AddField(
            model_name='objeto',
            name='obra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='prenomina15.Obra'),
        ),
    ]
