# Generated by Django 2.0.2 on 2019-08-22 17:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prenomina15', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='user_obra',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
