# Generated by Django 2.0.2 on 2019-08-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0002_obra_user_obra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='user_obra',
            new_name='usuarios',
        ),
    ]
