# Generated by Django 2.0.2 on 2019-08-23 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0003_auto_20190822_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='obra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prenomina15.Obra'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='gesc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='adm.EscalaSalarial'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='orden_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='entrada_datos.OT'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='actividad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='entrada_datos.Actividad'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='especialidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prenomina15.Especialidad'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='formato',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prenomina15.Formato'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='objeto',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prenomina15.Objeto'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='obra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prenomina15.Obra'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='trabajador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='Trabajador_del_Plano', to='ges_trab.Trabajador'),
        ),
    ]
