# Generated by Django 2.0.2 on 2019-09-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0005_auto_20190826_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='estado',
            field=models.CharField(default='', editable=False, max_length=3),
        ),
    ]
