# Generated by Django 2.0.2 on 2019-09-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0006_auto_20190917_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='estado',
            field=models.CharField(blank=True, default='', editable=False, max_length=3, null=True),
        ),
    ]
