# Generated by Django 2.0.2 on 2019-11-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0008_plano_rev_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='estado',
            field=models.CharField(choices=[('V', 'V'), ('GE', 'GE'), ('VPC', 'VPC')], default='', editable=False, max_length=3),
        ),
    ]
