# Generated by Django 2.0.2 on 2019-11-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0009_auto_20191125_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='tipo_doc',
            field=models.CharField(blank=True, choices=[('PL', 'PL'), ('MD', 'MD'), ('LM', 'LM'), ('PR', 'PR')], default='PL', editable=False, max_length=2),
        ),
    ]
