# Generated by Django 2.0.2 on 2019-11-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0010_plano_tipo_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='lm',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='md',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='especialidad',
            name='pr',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
