# Generated by Django 2.0.2 on 2019-11-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0011_auto_20191125_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='entregado',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
