# Generated by Django 2.0.2 on 2019-12-03 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0012_auto_20191129_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='tipo',
            field=models.CharField(choices=[('OT', 'Obra Turismo'), ('VT', 'Vivienda para Turismo'), ('R6', 'Resolucion 6')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='plano',
            name='tipo_doc',
            field=models.CharField(choices=[('PL', 'PL'), ('MD', 'MD'), ('LM', 'LM'), ('PR', 'PR')], default='PL', max_length=2),
        ),
    ]
