# Generated by Django 2.0.2 on 2019-12-03 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenomina15', '0013_auto_20191202_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='entregado',
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
