# Generated by Django 2.0.2 on 2019-12-08 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('prenomina15', '0015_auto_20191202_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant', models.PositiveIntegerField(default=1)),
                ('porciento',
                 models.CharField(choices=[('1.0', '100%'), ('0.7', '70%'), ('0.3', '30%')], default='', max_length=3)),
                ('horas_creadas', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                (
                    'horas_creadas_real',
                    models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5)),
                ('valor_retenido', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('valor_retenido_real',
                 models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('valor_real', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('valor_total_real', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6)),
                ('formato',
                 models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='prenomina15.Formato')),
                ('plano',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='prenomina15.Plano')),
            ],
        ),
    ]
