# Generated by Django 2.0.2 on 2019-12-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('prenomina15', '0016_catalogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='lm',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='md',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='pr',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=4),
        ),
    ]
