# Generated by Django 2.0.2 on 2019-12-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('prenomina15', '0017_auto_20191210_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidad',
            old_name='lm',
            new_name='lc',
        ),
        migrations.AlterField(
            model_name='plano',
            name='tipo_doc',
            field=models.CharField(choices=[('PL', 'PL'), ('MD', 'MD'), ('LC', 'LC'), ('PR', 'PR')], default='PL',
                                   max_length=2),
        ),
    ]
