# Generated by Django 2.0.2 on 2019-04-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ges_trab', '0001_initial'),
        ('entrada_datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoeficientePromedioSalario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeficiente', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_horas', models.PositiveIntegerField()),
                ('horas_ext', models.PositiveIntegerField(default=0)),
                ('tarifa_hor', models.DecimalField(decimal_places=6, editable=False, max_digits=7)),
                ('prod_reportada', models.PositiveIntegerField(editable=False)),
                ('actividad', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='entrada_datos.Actividad')),
                ('orden_trab', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='entrada_datos.OT')),
                ('trabajador', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='ges_trab.Trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='DatosAnual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_horas', models.PositiveIntegerField()),
                ('horas_ext', models.PositiveIntegerField(default=0)),
                ('tarifa_hor', models.DecimalField(decimal_places=6, editable=False, max_digits=7)),
                ('prod_reportada', models.PositiveIntegerField(editable=False)),
                ('fecha', models.DateField(editable=False)),
                ('prod_tecleada', models.PositiveIntegerField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entrada_datos.Actividad')),
                ('orden_trab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='entrada_datos.OT')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ges_trab.Trabajador')),
            ],
        ),
    ]
