# Generated by Django 2.0.2 on 2019-04-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ges_trab', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsidio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateField(verbose_name='Fecha de inicio')),
                ('hasta', models.DateField(verbose_name='Fecha de fin')),
                ('centro', models.CharField(max_length=200, verbose_name='Centro Asistencial')),
                ('medico', models.CharField(max_length=200, verbose_name='Nombre del médico')),
                ('fecha', models.DateField(verbose_name='Fecha de registro')),
                ('diagnostico', models.CharField(max_length=80, verbose_name='Diagnóstico')),
                ('por_ciento', models.CharField(choices=[('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100')], default=('50', '50'), max_length=3, verbose_name='Porciento a pagar')),
                ('dias', models.PositiveIntegerField(verbose_name='Cantidad de días a pagar')),
                ('tipo', models.CharField(choices=[('Inic.', 'Inicial'), ('Cont.', 'Continuado')], default=('Inic.', 'Inicial'), max_length=5, verbose_name='Tipo de certificado')),
                ('no_reg', models.PositiveIntegerField(default=1, verbose_name='Número del registro del certificado')),
                ('ent_72', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default=('Si', 'Si'), max_length=2, verbose_name='Entregado antes las 72 horas')),
                ('codigo_trab', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ges_trab.Trabajador')),
            ],
        ),
    ]
