# Generated by Django 2.0.2 on 2019-04-03 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antiguedad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.BooleanField()),
                ('pago_adicional', models.BooleanField()),
                ('porciento_5', models.BooleanField()),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CIES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.BooleanField()),
                ('pago_adicional', models.BooleanField()),
                ('porciento_30', models.BooleanField()),
                ('cies', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('dirige', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Departamento', to='adm.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='EscalaSalarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=8, unique=True)),
                ('coeficientes', models.DecimalField(decimal_places=2, max_digits=3)),
                ('salario_escala', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarifa_horaria', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('calificacion', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='adm.Calificacion')),
            ],
        ),
        migrations.CreateModel(
            name='SeccionSindical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='seccion',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='adm.SeccionSindical'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='unidad',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='adm.UnidadOrg'),
        ),
        migrations.AddField(
            model_name='cies',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.EscalaSalarial'),
        ),
        migrations.AddField(
            model_name='antiguedad',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adm.EscalaSalarial'),
        ),
    ]
