# Generated by Django 2.0.2 on 2019-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de registro')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Horas')),
                ('causal', models.CharField(choices=[('V', 'Vacaciones'), ('Cm', 'Certificado Médico'), ('LSS', 'Licencia sin Sueldo'), ('MI', 'Misión Internacionalista'), ('I', 'Interrupción'), ('B', 'Baja'), ('A', 'Alta'), ('M', 'Movilización'), ('E', 'Enfermo'), ('Fr', 'Receso Laboral Retribuido'), ('F', 'Prestación Social')], default=('V', 'Vacaciones'), max_length=3, verbose_name='Causal')),
            ],
        ),
        migrations.CreateModel(
            name='TarjetaCNC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septiembre', 'Septiembre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], default=('Enero', 'Enero'), max_length=12, verbose_name='Mes')),
                ('anno', models.PositiveIntegerField(default=2019, verbose_name='Año')),
                ('cant_dias', models.PositiveIntegerField(verbose_name='Cant. días')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Salario')),
            ],
        ),
    ]
