# Generated by Django 2.0.2 on 2019-04-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ges_trab', '0001_initial'),
        ('ausentismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacnc',
            name='codigo_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ges_trab.Trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='ausencia',
            name='codigo_trab',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ges_trab.Trabajador', verbose_name='Trabajador'),
        ),
    ]
